# 1. Đường dẫn kết nối tới Database PostgreSQL của bạn
spring.datasource.url=jdbc:postgresql://localhost:5432/alumnect
spring.datasource.username=postgres

# ⚠️ THAY MẬT KHẨU POSTGRESQL CỦA BẠN VÀO ĐÂY
spring.datasource.password=Admin

# 2. Cấu hình Hibernate tự động sinh bảng dữ liệu dựa trên code Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect