export { useIndustries, useCreateSalaryContribution } from './hooks/useSalary'
export { salaryApi } from './api/salaryApi'
export { industrySchema, salaryContributionSchema, createSalaryContributionSchema, MAX_GROSS_AMOUNT } from './model/salary'
export type { Industry, SalaryContribution, CreateSalaryContributionInput } from './model/salary'
export { ContributeSalaryModal } from './components/ContributeSalaryModal'
